project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning Blog"
  navbar:
    background: "#112a39"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/charliemoore00/
      - icon: linkedin
        href: https://www.linkedin.com/in/charlie-moore-b55340214/

format:
  html:
    title-block-banner: img/landscape.png
    title-block-banner-color: white
    theme: cosmo
    css: styles.css





